import type { Metadata } from "next";
import { Lexend } from "next/font/google";
import "./globals.css";

import { cn } from "@/lib/utils";

export const lexend = Lexend({
	variable: "--font-lexend",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={cn("min-h-screen antialiased dark", lexend.variable)}
			>
				{children}
			</body>
		</html>
	);
}
