import type { Metadata } from "next";
import { lexend } from "./font";
import "./globals.css";

import { cn } from "@/lib/utils";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="scroll-smooth">
			<body
				className={cn("min-h-screen antialiased dark", lexend.variable)}
			>
				{children}
			</body>
		</html>
	);
}
